---
name: macOS framework
on:
  push:
    branches:
      - packaging-sdl2
jobs:
  macos-framework:
    name: MacOS (Framework)
    runs-on: macos-latest
    steps:
      - name: Dependencies
        run: brew install cmake ninja tree
      - name: SDL2
        run: |
          SDL2_VERSION=2.0.16
          curl -LO https://libsdl.org/release/SDL2-$SDL2_VERSION.dmg
          hdiutil attach -verbose SDL2-$SDL2_VERSION.dmg
          mkdir -p $GITHUB_WORKSPACE/externals/
          cat <<EOF > $GITHUB_WORKSPACE/externals/sdl2-config.cmake
            find_library(SDL2_LIBRARIES SDL2 PATHS /Volumes/SDL2)
            find_path(SDL2_INCLUDE_DIRS SDL.h PATHS /Volumes/SDL2/SDL2.framework PATH_SUFFIXES Headers)
            message(STATUS "SDL2: \${SDL2_LIBRARIES} / \${SDL2_INCLUDE_DIRS}")
          EOF
          tree /Volumes/SDL2
      - name: SeriousProton Checkout
        uses: actions/checkout@v2
        with:
          repository: gcask/SeriousProton
          path: SeriousProton
      - name: EmptyEpsilon Checkout
        uses: actions/checkout@v2
        with:
          path: EmptyEpsilon
      - name: Build
        run: |
          mkdir -p _build_macos
          cd _build_macos
          cmake ../EmptyEpsilon -G Ninja -DCPACK_GENERATOR=DragNDrop -DSDL2_DIR=$GITHUB_WORKSPACE/externals -DWARNING_IS_ERROR=1
          cmake --build . --config RelWithDebInfo --parallel --target EmptyEpsilon --verbose
          ls -l /Volumes
          ls -l /Volumes/SDL2
          ls -l /Volumes/SDL2/SDL2.framework
          cpack --config CPackConfig.cmake --verbose
          ls -l /Volumes/SDL2/
